### ISSUE TITLE
Przydaloby sie sprawdzic czy nie schodzimy ponizej zera i wypisac info o tym ile zostalo zycia :)

### ISSUE THREAD

**Issue by bulakowy** [xtower/arena#1]
https://github.com/xtower/arena/blob/8649b22405d9eccb12bb09382cb8e310af2260a7/src/main/java/com/example/arena/Creature.java#L146

**Comment by xtower** [comment]
To będzie ficzer. Stworki mogą być mniej lub bardziej martwe - bardziej martwego np trudniej ożywić.
